In [31]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[4,5,6],[7,8,9]])

print ("Add : \n", np.add(array1,array2))



Add : 
 [[ 5  7  9]
 [11 13 15]]


In [32]:
print("Add: \n" ,np.add(array1,array2))
print("\n Substraction: \n",np.subtract(array1,array2))
print("\n Multiply: \n", np.multiply(array1,array2))
print("\n Divide: \n", np.divide(array1,array2))

Add: 
 [[ 5  7  9]
 [11 13 15]]

 Substraction: 
 [[-3 -3 -3]
 [-3 -3 -3]]

 Multiply: 
 [[ 4 10 18]
 [28 40 54]]

 Divide: 
 [[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]


In [33]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([3,5,7,9])

result1 = array1[np.in1d(array1,array2)]

print (result1)

[3 5]
